# Generated by Django 3.2.4 on 2021-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Mobile', models.IntegerField(max_length=10, null=True)),
                ('State', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50)),
                ('Pin', models.IntegerField(max_length=6, null=True)),
                ('Landmark', models.CharField(max_length=100)),
            ],
        ),
    ]
